name: oauth1
version: 3.0.0
description: "\"RFC 5849: The OAuth 1.0 Protocol\" client implementation for Dart."
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.0
  http: ^1.0.0

dev_dependencies:
  lints: 2.1.1
  test: ^1.16.5
